### ISSUE TITLE
课时冲突

### ISSUE THREAD

**Issue by Lemon-412** [KanadeSiina/SMS-SQL#4]
学生在选课时，允许选择课时冲突的课。

**Comment by Lemon-412** [comment]
（但这格式咋检测冲突啊

**Comment by cubercsl** [comment]
真的牛逼

**Comment by Lemon-412** [comment]
This issue has been ignored but remain unfixed.

**Comment by akamya997** [comment]
Student should be responsible for what they did by themselves.
